name: pushup_bro
description: Track your pushups with ease using the sensors in your AirPods!
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  carbon_icons: ^0.0.1+2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  intl_utils: ^2.8.1
  rive: ^0.10.1

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^4.14.0
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/rive/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: assets/l10n
  ouput_dir: lib/generated

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    rive: true
